# Generated by Django 3.1.5 on 2021-01-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210108_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fees',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
    ]
