# Generated by Django 3.1.5 on 2021-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20210109_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
